### ISSUE TITLE
launch site.launch errors

### ISSUE THREAD

**Issue by hayoung-kim** [Hayoung-Kim/udacity-carnd-capstone#1]
I downloaded rosbag file for testing tl_detection. the rosbag file provided by udacity can be downloaded: https://drive.google.com/uc?id=0B2_h37bMVw3iYkdJTlRSUlJIamM&export=download

At zip-extracted folder, 
```
>> rosbag play -l just_traffic_light.bag
```

and at another terminal
```
>> cd udacity-carnd-capstone/ros/
>> roslaunch launch/site.launch
```

you can see the error message as below:
```
[ERROR] [1514915649.863526]: Failed to find camera to map transform
[ERROR] [1514915649.863895]: bad callback: <bound method TLDetector.image_cb of <__main__.TLDetector object at 0x7fcdad5f63d0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/hayoung/carnd/udacity-carnd-capstone/ros/src/tl_detector/tl_detector.py", line 114, in image_cb
    light_wp, state = self.process_traffic_lights()
  File "/home/hayoung/carnd/udacity-carnd-capstone/ros/src/tl_detector/tl_detector.py", line 244, in process_traffic_lights
    state = self.get_light_state(self.lights[tl_idx])
  File "/home/hayoung/carnd/udacity-carnd-capstone/ros/src/tl_detector/tl_detector.py", line 189, in get_light_state
    x, y = self.project_to_image_plane(light.pose.pose.position)
  File "/home/hayoung/carnd/udacity-carnd-capstone/ros/src/tl_detector/tl_detector.py", line 164, in project_to_image_plane
    R = PyKDL.Rotation.Quaternion(*rot)
UnboundLocalError: local variable 'rot' referenced before assignment
```

I shared image on slack.

**Comment by hayoung-kim** [comment]
I guess this issue can help us! 
[https://github.com/udacity/CarND-Capstone/issues/24](https://github.com/udacity/CarND-Capstone/issues/24)
I'll continue tomorrow.....
